replicaCount: 1

image:
  repository: rucio/rucio-server
  tag: latest

config:
  database:
    default: "postgresql+psycopg://rucio:secret@postgres-postgresql/rucio"
    schema: "test"

ingress:
  enabled: true
  path: /
  hosts: 
    - rucio-server.info
